# Generated by Django 3.0 on 2022-04-23 15:48

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('localizador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_entry', models.DateField()),
                ('date_exit', models.DateField()),
                ('type_room', models.TextField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('QUADRUPLE', 'Quadruple')], default='DOUBLE', max_length=20)),
                ('price', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
            ],
        ),
    ]
